"""MLX-native e3nn runtime."""

from e3nn_core import Irrep, Irreps, MulIrrep, su2_generators, wigner_3j

from .backend import MLXBackend, mlx_backend
from .irreps_array import IrrepsArray
from .nn_gate import Gate
from .nn_linear import Linear
from .nn_norm import Norm
from .ops_rotations import (
    angles_to_axis_angle,
    angles_to_matrix,
    angles_to_quaternion,
    angles_to_xyz,
    axis_angle_to_angles,
    axis_angle_to_matrix,
    axis_angle_to_quaternion,
    compose_angles,
    compose_axis_angle,
    compose_quaternion,
    identity_angles,
    inverse_angles,
    irreps_wigner_d,
    matrix_to_angles,
    matrix_to_axis_angle,
    matrix_to_quaternion,
    matrix_x,
    matrix_y,
    matrix_z,
    quaternion_to_angles,
    quaternion_to_axis_angle,
    quaternion_to_matrix,
    rand_angles,
    rand_axis_angle,
    rand_matrix,
    rand_quaternion,
    rotation_matrix,
    wigner_d,
    xyz_to_angles,
)
from .ops_sh import (
    SphericalHarmonics,
    SphericalHarmonicsAlphaBeta,
    sh,
    spherical_harmonics,
    spherical_harmonics_alpha_beta,
)
from .ops_tp import (
    ElementwiseTensorProduct,
    FullTensorProduct,
    FullyConnectedTensorProduct,
    TensorProduct,
    TensorSquare,
    tensor_product,
    tensor_product_plan,
)

__all__ = [
    "ElementwiseTensorProduct",
    "FullTensorProduct",
    "FullyConnectedTensorProduct",
    "Gate",
    "Irrep",
    "Irreps",
    "IrrepsArray",
    "Linear",
    "MLXBackend",
    "MulIrrep",
    "Norm",
    "SphericalHarmonics",
    "SphericalHarmonicsAlphaBeta",
    "TensorProduct",
    "TensorSquare",
    "angles_to_axis_angle",
    "angles_to_matrix",
    "angles_to_quaternion",
    "angles_to_xyz",
    "axis_angle_to_angles",
    "axis_angle_to_matrix",
    "axis_angle_to_quaternion",
    "compose_angles",
    "compose_axis_angle",
    "compose_quaternion",
    "identity_angles",
    "inverse_angles",
    "irreps_wigner_d",
    "matrix_to_angles",
    "matrix_to_axis_angle",
    "matrix_to_quaternion",
    "matrix_x",
    "matrix_y",
    "matrix_z",
    "mlx_backend",
    "rotation_matrix",
    "quaternion_to_angles",
    "quaternion_to_axis_angle",
    "quaternion_to_matrix",
    "rand_angles",
    "rand_axis_angle",
    "rand_matrix",
    "rand_quaternion",
    "sh",
    "spherical_harmonics",
    "spherical_harmonics_alpha_beta",
    "su2_generators",
    "tensor_product",
    "tensor_product_plan",
    "wigner_3j",
    "wigner_d",
    "xyz_to_angles",
]
